name = "PredatorPrey"
uuid = "4e2b2dba-6b4e-4277-831b-628fdf547a64"
authors = ["Rajith Vidanaarachchi"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
